import * as z from "zod";


export const CustodyElementSchema = z.object({
    "id": z.number(),
    "name": z.string(),
    "custody_amount": z.number(),
    "custody_type": z.string(),
    "refuse_reason": z.union([z.boolean(), z.string()]),
    "cancel_reason": z.boolean(),
    "custody_reason_id": z.array(z.union([z.number(), z.string()])),
    "custody_reason": z.string(),
    "employee_id": z.array(z.union([z.number(), z.string()])),
    "is_have_close_custody": z.boolean(),
    "is_have_replace_custody": z.boolean(),
    "state": z.string(),
    "hide_payment_order": z.boolean(),
    "payment_order_id": z.boolean(),
    "order_date": z.string(),
    "company_id": z.array(z.union([z.number(), z.string()])),
    "account_id": z.array(z.union([z.number(), z.string()])),
    "journal_id": z.boolean(),
    "payment_state": z.boolean(),
    "readonly_by_pass": z.boolean(),
    "payment_move_line_ids": z.array(z.any()),
    "check_custody_remain_amount": z.boolean(),
    "active": z.boolean(),
    "res_model": z.string(),
    "is_from_mobile": z.boolean(),
    "mobile_approvals_ids": z.array(z.any()),
    "website_message_ids": z.array(z.any()),
    "message_follower_ids": z.array(z.number()),
    "message_ids": z.array(z.number()),
    "message_last_post": z.boolean(),
    "create_uid": z.array(z.union([z.number(), z.string()])),
    "create_date": z.coerce.date(),
    "write_uid": z.array(z.union([z.number(), z.string()])),
    "write_date": z.coerce.date(),
    "number": z.string(),
    "sector_id": z.array(z.union([z.number(), z.string()])),
    "administration_id": z.array(z.union([z.number(), z.string()])),
    "job_id": z.array(z.union([z.number(), z.string()])),
    "degree_id": z.array(z.union([z.number(), z.string()])),
    "check_authority_owner": z.boolean(),
    "custody_paid_amount": z.number(),
    "custody_remain_amount": z.number(),
    "bank_id": z.array(z.union([z.number(), z.string()])),
    "acc_number": z.string(),
    "is_dm": z.boolean(),
    "payments_widget": z.string(),
    "is_action_send": z.boolean(),
    "account_move_number": z.string(),
    "account_move_id": z.boolean(),
    "department_global_id": z.array(z.union([z.number(), z.string()])),
    "message_is_follower": z.boolean(),
    "message_partner_ids": z.array(z.number()),
    "message_channel_ids": z.array(z.any()),
    "message_unread": z.boolean(),
    "message_unread_counter": z.number(),
    "message_needaction": z.boolean(),
    "message_needaction_counter": z.number(),
    "display_name": z.string(),
    "__last_update": z.coerce.date(),
});
export type CustodyElement = z.infer<typeof CustodyElementSchema>;
